name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github 
        settings-path: ${{ github.workspace }} 

    - name: Build and Publish with Maven
      run: >
        mvn -B deploy
        -s $GITHUB_WORKSPACE/settings.xml
        -Dspring.datasource.url=${{ secrets.DB_URL }}
        -Dspring.datasource.username=${{ secrets.DB_USERNAME }}
        -Dspring.datasource.password=${{ secrets.DB_PASSWORD }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
